B : 8      # Num of frequency bands
N : 6      # Num of users
L : 10      # RF chains
M : 12     # Tx antennas

create_dataset : False
train_size : 1000
valid_size : 100
test_size : 100

num_of_iter_pga : 40 # num classical pga iterations
num_of_iter_pga_unf : 5 # num unfolded pga iterations
proj_iter_rate : 1000 # num iterations between each proj


# training parameters
train : True
mu_matrix : True
lr : 0.01
epochs : 1
batch_size : 100  # batch size
loss : "one_iter" # "all_iter" "some_iter"
full_grad_Wd_iter : [1,3,4] #iterations on which to do full grad for dWd

use_cuda : True
Wa_G_I : False
Wa_G_Ones : True
