B : 8      # Num of frequency bands
N : 6      # Num of users
L : 10      # RF chains
M : 12     # Tx antennas

train_size : 1000
valid_size : 100
test_size : 100

num_of_iter_pga : 40 # num classical pga iterations
num_of_iter_pga_unf : 5 # num unfolded pga iterations
proj_iter_rate : 1000 # num iterations between each proj


# training parameters
train : True
mu_matrix : True
lr : 0.01
epochs : 5000
batch_size : 100  # batch size
loss_only_one_iter : False

use_cuda : True
Wa_G_I : False
Wa_G_Ones : False
