B : 8      # Num of frequency bands
N : 6      # Num of users
M : 12     # Tx antennas
L : 10      # RF chains

dataset_type : "QUAD" # "Rayleigh"
Quad_data_path : 'H_1200Channels_8B_12M_6N.mat'
Rayleigh_data_path : Rayleigh_dataset.pt.pt
create_IID_dataset : False #only relevant if IID dataset chosen
train_size : 1000
valid_size : 100
test_size : 100

num_of_iter_pga : 200 # num classical pga iterations
num_of_iter_pga_unf : 5 # num unfolded pga iterations

# training parameters
train : False
mu_matrix : True
lr : 0.01
epochs : 5000
batch_size : 100  # batch size
loss : "one_iter" # "all_iter" "some_iter"
model : Important_runs/QUAD_SET__8B__6N__12M__10L/D24_M07_h22_m12__QUAD_SET__K_5__loss_one_iter__WaConst_True__Q_8__dWdAlt_True/PGA_model.pth #Only used when train == False

#dWd options
full_grad_Wd_iter : [0,4] #iterations on which to do full grad for dWd --- CURRENTLY HARD CODED TO BE OFF
approx_dWd : True
iters_to_approx : [1,3] #first iter is 0
use_cuda : True

#dWa options
Wa_constrained : False
Wa_G_I : False
Wa_G_Ones : True
Freq_bins_for_Wa_grad : 8 #Instead of summing B freq bins, randomly choose Wa_B_grad bins 
